# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/c/PiFaceCAD

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/c/PiFaceCAD

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/c/PiFaceCAD/CMakeFiles /home/pi/c/PiFaceCAD/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/c/PiFaceCAD/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named piface

# Build rule for target.
piface: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 piface
.PHONY : piface

# fast build rule for target.
piface/fast:
	$(MAKE) -f CMakeFiles/piface.dir/build.make CMakeFiles/piface.dir/build
.PHONY : piface/fast

commonLcd.o: commonLcd.c.o

.PHONY : commonLcd.o

# target to build an object file
commonLcd.c.o:
	$(MAKE) -f CMakeFiles/piface.dir/build.make CMakeFiles/piface.dir/commonLcd.c.o
.PHONY : commonLcd.c.o

commonLcd.i: commonLcd.c.i

.PHONY : commonLcd.i

# target to preprocess a source file
commonLcd.c.i:
	$(MAKE) -f CMakeFiles/piface.dir/build.make CMakeFiles/piface.dir/commonLcd.c.i
.PHONY : commonLcd.c.i

commonLcd.s: commonLcd.c.s

.PHONY : commonLcd.s

# target to generate assembly for a file
commonLcd.c.s:
	$(MAKE) -f CMakeFiles/piface.dir/build.make CMakeFiles/piface.dir/commonLcd.c.s
.PHONY : commonLcd.c.s

piface.o: piface.c.o

.PHONY : piface.o

# target to build an object file
piface.c.o:
	$(MAKE) -f CMakeFiles/piface.dir/build.make CMakeFiles/piface.dir/piface.c.o
.PHONY : piface.c.o

piface.i: piface.c.i

.PHONY : piface.i

# target to preprocess a source file
piface.c.i:
	$(MAKE) -f CMakeFiles/piface.dir/build.make CMakeFiles/piface.dir/piface.c.i
.PHONY : piface.c.i

piface.s: piface.c.s

.PHONY : piface.s

# target to generate assembly for a file
piface.c.s:
	$(MAKE) -f CMakeFiles/piface.dir/build.make CMakeFiles/piface.dir/piface.c.s
.PHONY : piface.c.s

spiLcd.o: spiLcd.c.o

.PHONY : spiLcd.o

# target to build an object file
spiLcd.c.o:
	$(MAKE) -f CMakeFiles/piface.dir/build.make CMakeFiles/piface.dir/spiLcd.c.o
.PHONY : spiLcd.c.o

spiLcd.i: spiLcd.c.i

.PHONY : spiLcd.i

# target to preprocess a source file
spiLcd.c.i:
	$(MAKE) -f CMakeFiles/piface.dir/build.make CMakeFiles/piface.dir/spiLcd.c.i
.PHONY : spiLcd.c.i

spiLcd.s: spiLcd.c.s

.PHONY : spiLcd.s

# target to generate assembly for a file
spiLcd.c.s:
	$(MAKE) -f CMakeFiles/piface.dir/build.make CMakeFiles/piface.dir/spiLcd.c.s
.PHONY : spiLcd.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... piface"
	@echo "... commonLcd.o"
	@echo "... commonLcd.i"
	@echo "... commonLcd.s"
	@echo "... piface.o"
	@echo "... piface.i"
	@echo "... piface.s"
	@echo "... spiLcd.o"
	@echo "... spiLcd.i"
	@echo "... spiLcd.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

